[package]
name = "conllu_pos_dataset"
version = "0.1.0"
authors = ["Sacha <sacha.arbonel@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conllu = "0.5.1"
